#ifndef PSVR2_UMH_INTERNAL_H
#define PSVR2_UMH_INTERNAL_H

#include "psvr2/common.h"

#define PSVR2_UMH_SHELL_OFFSET UINT64_C(0x00)
#define PSVR2_UMH_SHELL_ARG_OFFSET UINT64_C(0x08)
#define PSVR2_UMH_COMMAND_OFFSET UINT64_C(0x10)
#define PSVR2_UMH_RESULT_OFFSET UINT64_C(0xf0)
#define PSVR2_UMH_ARGV_OFFSET UINT64_C(0x100)
#define PSVR2_UMH_COMMAND_CAPACITY 224U
#define PSVR2_UMH_PENDING_RESULT UINT64_C(0xdead)
#define PSVR2_UMH_WORK_STATE UINT64_C(0x0fffffffe0)
#define PSVR2_UMH_OUTPUT_LIMIT 65536U
#define PSVR2_UMH_OUTPUT_PATH "/tmp/.kout"
#define PSVR2_UMH_OUTPUT_NAME ".kout"

#endif
